"""
Unkept local server
===================
Single FastAPI process that hosts the AI-backed parts of the Unkept pipeline:

  POST /embed     — CLIP ViT-B/32 image embeddings used by clusterSemantic.js
                    during Phase 1 (selection). Always-on; model loads at
                    startup.

  POST /caption   — Per-chapter Wrapped-style captions generated by Claude
                    (Phase 3 / PR3A — see IMPLEMENTATION-PLAN.md). Only
                    active when ANTHROPIC_API_KEY is set; the response is a
                    Server-Sent Events stream of text deltas.

Photos never leave the user's device during Phase 1. The caption endpoint
receives thumbnails (data URLs) only when the user opts in on the upload
page.

Run:
    uvicorn main:app --port 8000 --reload
"""

import base64
import io
import json
import logging
import os
import re
import time
from collections.abc import Iterator

import anthropic
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from PIL import Image
from pydantic import BaseModel
from sentence_transformers import SentenceTransformer

logging.basicConfig(level=logging.INFO)
log = logging.getLogger(__name__)

app = FastAPI(title="Unkept local server")

# Allow requests from Vite dev servers on any localhost port.
app.add_middleware(
    CORSMiddleware,
    allow_origin_regex=r"^https?://(localhost|127\.0\.0\.1|\[::1\])(:\d+)?$",
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

_DATA_URL_RE = re.compile(r"^data:(image/[a-zA-Z0-9.+-]+);base64,(.+)$", re.DOTALL)


def _decode_data_url(data_url: str) -> tuple[str, bytes]:
    """Return (media_type, raw_bytes) from a base64-encoded image data URL."""
    m = _DATA_URL_RE.match(data_url)
    if not m:
        raise ValueError("Expected data:image/<type>;base64,<...>")
    return m.group(1), base64.b64decode(m.group(2))


# ---------------------------------------------------------------------------
# Embedding (CLIP) — Phase 1
# ---------------------------------------------------------------------------

log.info("Loading CLIP ViT-B/32 — downloading on first run (~350 MB)…")
_clip = SentenceTransformer("clip-ViT-B-32")
log.info("CLIP ready.")


class ImageItem(BaseModel):
    id: str
    data: str  # data:image/jpeg;base64,<...>


class EmbedRequest(BaseModel):
    images: list[ImageItem]


class EmbedResponse(BaseModel):
    embeddings: list[dict]  # [{id, vector: [float × 512]}]


def _decode_image(data_url: str) -> Image.Image:
    _, raw = _decode_data_url(data_url)
    return Image.open(io.BytesIO(raw)).convert("RGB")


@app.get("/health")
def health():
    return {
        "status": "ok",
        "embed": "clip-ViT-B-32",
        "caption_enabled": bool(_anthropic_key()),
    }


@app.post("/embed", response_model=EmbedResponse)
def embed(req: EmbedRequest):
    if not req.images:
        return EmbedResponse(embeddings=[])

    t0 = time.perf_counter()

    try:
        pil_images = [_decode_image(item.data) for item in req.images]
    except Exception as exc:
        raise HTTPException(status_code=400, detail=f"Image decode failed: {exc}")

    vectors = _clip.encode(
        pil_images,
        batch_size=32,
        normalize_embeddings=True,
        show_progress_bar=False,
        convert_to_numpy=True,
    )

    elapsed = (time.perf_counter() - t0) * 1000
    log.info("Embedded %d images in %.0f ms", len(req.images), elapsed)

    return EmbedResponse(
        embeddings=[
            {"id": item.id, "vector": vectors[i].tolist()}
            for i, item in enumerate(req.images)
        ]
    )


# ---------------------------------------------------------------------------
# Caption (Claude) — Phase 3 / opt-in
# ---------------------------------------------------------------------------

CAPTION_MODEL = "claude-haiku-4-5-20251001"
CAPTION_MAX_TOKENS = 200

# Placeholder system prompt — iterate from here while tuning the caption
# voice (Wrapped-style, evocative, ≤8 words, etc.). The cache_control block
# below means longer prompts get prompt caching for free.
CAPTION_SYSTEM_PROMPT = "Describe this image"


def _anthropic_key() -> str | None:
    return os.environ.get("ANTHROPIC_API_KEY") or None


class CaptionRequest(BaseModel):
    chapter_id: str
    hero_image: str  # data URL of the hero thumbnail
    day_index: int | None = None
    date: str | None = None
    location_label: str | None = None
    photo_count: int | None = None


def _chapter_context(req: CaptionRequest) -> str:
    """Compact context block that sits next to the image in the user turn."""
    parts: list[str] = []
    if req.day_index is not None:
        parts.append(f"Day {req.day_index} of the trip.")
    if req.date:
        parts.append(f"Captured on {req.date}.")
    if req.location_label:
        parts.append(f"Location: {req.location_label}.")
    if req.photo_count is not None:
        parts.append(f"{req.photo_count} photos in this chapter.")
    return " ".join(parts) or "Trip photo."


def _sse(event: str, data: str) -> str:
    """Format one SSE message. Data is JSON-encoded so newlines survive."""
    return f"event: {event}\ndata: {json.dumps(data)}\n\n"


@app.post("/caption")
def caption(req: CaptionRequest):
    key = _anthropic_key()
    if not key:
        raise HTTPException(
            status_code=503,
            detail="ANTHROPIC_API_KEY is not set on the server.",
        )

    try:
        media_type, raw = _decode_data_url(req.hero_image)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    b64 = base64.b64encode(raw).decode("ascii")

    client = anthropic.Anthropic(api_key=key)

    def event_stream() -> Iterator[str]:
        t0 = time.perf_counter()
        try:
            with client.messages.stream(
                model=CAPTION_MODEL,
                max_tokens=CAPTION_MAX_TOKENS,
                # cache_control on the system block lets Anthropic reuse the
                # tokens across every chapter request in a story (within the
                # cache TTL). Today the prompt is too short to clear the
                # cache threshold so this is a no-op; as the prompt grows
                # we get the savings without code changes.
                system=[
                    {
                        "type": "text",
                        "text": CAPTION_SYSTEM_PROMPT,
                        "cache_control": {"type": "ephemeral"},
                    }
                ],
                messages=[
                    {
                        "role": "user",
                        "content": [
                            {
                                "type": "image",
                                "source": {
                                    "type": "base64",
                                    "media_type": media_type,
                                    "data": b64,
                                },
                            },
                            {"type": "text", "text": _chapter_context(req)},
                        ],
                    }
                ],
            ) as stream:
                for text in stream.text_stream:
                    if text:
                        yield _sse("delta", text)
            elapsed = (time.perf_counter() - t0) * 1000
            log.info("Captioned chapter %s in %.0f ms", req.chapter_id, elapsed)
            yield _sse("done", "")
        except anthropic.APIError as exc:
            log.warning("Caption failed for chapter %s: %s", req.chapter_id, exc)
            yield _sse("error", str(exc))

    return StreamingResponse(
        event_stream(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            # disable buffering in any intermediate proxy so deltas flush
            "X-Accel-Buffering": "no",
        },
    )
